repos:
  - repo: https://github.com/pre-commit/mirrors-eslint.git
    rev: v5.16.0
    hooks:
      - &eslint
        id: eslint
        types: [javascript]
        additional_dependencies:
          - eslint@5.16.0
          - typescript@3.5.2
          - "@typescript-eslint/eslint-plugin@1.10.2"
          - "@typescript-eslint/parser@1.10.2"
      - <<: *eslint
        alias: eslint:ts
        name: eslint:ts
        types: [ts]
  - repo: https://github.com/prettier/prettier.git
    rev: 1.18.2
    hooks:
      - id: prettier
        exclude: "^templates/|^static/data/"
        args: [--loglevel=warn]
  - repo: local
    hooks:
      - id: typescript
        name: typescript
        entry: tsc
        language: node
        "types": [ts]
        args: [--noEmit, --project, tsconfig.json]
        pass_filenames: false
        additional_dependencies: ["typescript@3.5.2"]
